name: Run Cypress Tests

on:
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm install

    - name: Run Cypress tests
      run: |
        npx cypress run

    - name: Upload Cypress report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: cypress/reports/html/